eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: eureka-client-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared