server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client-ribbon
  zipkin:
    base-url: http://localhost:8768
  sleuth:
    sampler:
      percentage: 1.0